#!/bin/sh

# Wrapper options have to be set before any other opts.
#
# --always-yes - answers "yes" to all interactive questions

set -eu

always_yes=false

while :; do
  case "${1-}" in
    --always-yes)
      always_yes=true
      ;;
    *)
      break
      ;;
  esac

  shift
done

if [ "$always_yes" = true ]; then
  # Ignore "Broken pipe" message from the `printf` command.
  #
  # We cannot use `yes` as BEAM ignores SIGPIPE and on macOS and BSD
  # this behaviour is inherited by child processes which in turn means
  # that `yes` wouldn't stop after docker-compose exits and would
  # use 100% of CPU aterwards. Using `printf` we can print only
  # a finite number of 'y's which solves this issue.
  printf 'y\n%.0s' {1..1000} 2>/dev/null | docker-compose "$@"
else
  docker-compose "$@"
fi
